### ISSUE TITLE
Feature: migrate lark / feishu to official Node SDK

### ISSUE THREAD

**Issue by MaikoTan** [satorijs/satori#100]
## Summary

Lark has the [official Node SDK](https://github.com/larksuite/node-sdk) now, might possible to migrate to it.

**Comment by shigma** [comment]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/33423008/230564089-5c9fd3ea-c1d5-4bcf-b679-0252e0ef1068.png">

😕

**Comment by MaikoTan** [comment]
> https://github.com/larksuite/node-sdk/blob/16aa4a50be48ca79a350d69629952628fd2b83b3/package.json#L31-L38
> 
> 😕 

😭
