### ISSUE TITLE
Bug: QQ频道无法回复消息

### ISSUE THREAD

**Issue by idanran** [satorijs/satori#102]
使用了 onebot 适配器。
```
[W] gocqhttp 转换消息 [CQ:reply,id=BAgNTrIhxFqMAAAAAAadU8gAAAAAAAAABw==] 到MiraiGo Element时出现错误: reply消息中必须包含 text 或 id.
```

Koishi Core: 4.12.5

**Comment by shigma** [comment]
这里的 id 是真实的 message id 吗？可以用 inspect 插件试试？

**Comment by idanran** [comment]
> 这里的 id 是真实的 message id 吗？可以用 inspect 插件试试？

![Screenshot 2023-04-28 185141](https://user-images.githubusercontent.com/96647698/235129526-6f1cbcbc-d1d3-4fc6-a728-280bf5e575aa.png)

**Comment by shigma** [comment]
这个跟 #103 一样，应该都是 go-cqhttp 对 CQ:reply 的支持不足。

**Comment by idanran** [comment]
> 这个跟 #103 一样，应该都是 go-cqhttp 对 CQ:reply 的支持不足。建议前往 go-cqhttp 仓库提交 issue。

Mrs4s/go-cqhttp#2120

**Comment by shigma** [comment]
go-cqhttp 已经停止维护。
