### ISSUE TITLE
Bug: QQ频道的Session缺少`quote`字段

### ISSUE THREAD

**Issue by idanran** [satorijs/satori#103]
使用了 onebot 适配器。

复现步骤：
1. 用户引用任意消息并发送
2. 机器人打印 session
3. 找不到 session.quote

Koishi Core: 4.12.5

**Comment by shigma** [comment]
我没有能上 QQ 频道的号，有没有人能帮忙抓一个包？

前往 `adapters/onebot/lib` 的 `adaptMessage` 方法，在函数体内加第一行 `console.log(message)`。然后发送一个引用回复，把命令行输出的内容发出来。如果可以的话非常感谢。

**Comment by shigma** [comment]
那从这个 payload 看起来确实没法判断 quote 啊，正常来说 quote 应该有个 CQ:reply 的，或许应该给 go-cqhttp 那边提 issue？

**Comment by idanran** [comment]
> 那从这个 payload 看起来确实没法判断 quote 啊，正常来说 quote 应该有个 CQ:reply 的，或许应该给 go-cqhttp 那边提 issue？

提好了 Mrs4s/go-cqhttp#2120

**Comment by shigma** [comment]
go-cqhttp 现已停止维护。
