### ISSUE TITLE
登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45

### ISSUE THREAD

**Issue by metaoneA** [satorijs/satori#104]
adapter-onebot 配置QQ用户密码，验证无法通过，启动服务报错

**Comment by metaoneA** [comment]
adapter-onebot 5.6.7
kshi 4.12.6

**Comment by Lipraty** [comment]
请前往论坛 810 贴：https://k.ilharp.cc/810

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by shigma** [comment]
gocq 相关问题不属于本仓库的讨论范畴，请前往 gocq 仓库或论坛 810 贴进行讨论。
