### ISSUE TITLE
无法正常登录账号

### ISSUE THREAD

**Issue by Star-Sum** [satorijs/satori#106]
QQ账号无法正常登录。账号状态正常，无账号冻结与密码错误情况，使用扫码与抓取滑条方式皆无法正常登录。

**Comment by HuanLinOTO** [comment]
没有 log 没有截图，我只能帮你算一卦
![ORV}D 45S89JF4H%HVDT V2](https://user-images.githubusercontent.com/94176676/235283946-1f33383c-8ee2-4b85-a46c-06755b9ab508.jpg)

**Comment by Star-Sum** [comment]
> 没有 log 没有截图，我只能帮你算一卦 ![ORV}D 45S89JF4H%HVDT V2](https://user-images.githubusercontent.com/94176676/235283946-1f33383c-8ee2-4b85-a46c-06755b9ab508.jpg)

![image](https://user-images.githubusercontent.com/74635178/235284063-9355c403-bf1d-4c0e-a19d-6cb824d31393.png)

**Comment by HuanLinOTO** [comment]
更新 Onebot 适配器到最新版本试试，或者重新安装依赖

**Comment by ilharp** [comment]
Duplicate of #104

**Comment by Star-Sum** [comment]
> 更新 Onebot 适配器到最新版本试试，或者重新安装依赖

![image](https://user-images.githubusercontent.com/74635178/235284641-ee48ede6-8aa0-49d1-81c5-8ee57cf41237.png)
更新之后的提示信息

**Comment by HuanLinOTO** [comment]
他都告诉你了怎么办了

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by ilharp** [comment]
登录相关问题请前往论坛进行讨论。这是 Satori 项目的仓库，登录问题不由此项目负责。

**Comment by shigma** [comment]
此问题与本仓库无关，请前往 go-cqhttp 仓库或者 Koishi 论坛交流。
