### ISSUE TITLE
BUG Maximum number of redirects exceeded（配置代理以后提示重定向次数过多）

### ISSUE THREAD

**Issue by Joyboy-s** [satorijs/satori#107]
![image](https://github.com/satorijs/satori/assets/71379728/0bebb3c2-43f1-4619-a95b-61ca90a0fe3e)
![image](https://github.com/satorijs/satori/assets/71379728/4657399a-c12a-424c-ab2a-ba5452c5a6ec)

**Comment by MaikoTan** [comment]
This looks like a network issue on your proxy server, please check if there is another approach to achieve you connecting to discord instead.

**Comment by Joyboy-s** [comment]
代理更换为 socks://127.0.0.1:7890
![image](https://github.com/satorijs/satori/assets/71379728/f354c461-eb7d-4d40-acf1-cfeea79830b5)
