### ISSUE TITLE
Feature: 请问要如何回复消息到飞书的 thread 中

### ISSUE THREAD

**Issue by tzwm** [satorijs/satori#111]
理论上回复的时候带上上一条消息的 message_id 应该就可以，但我不是很清楚我在用 koishi `session.send` 的时候如何带上 message_id 参数。

**Comment by shigma** [comment]
session.send 会自动带上上一条消息的 id。可能飞书适配器并没有用这个特性。

**Comment by MaikoTan** [comment]
What is the thread that you referring to? Is there documents about this? It may be not implemented yet.

**Comment by tzwm** [comment]
The thread is like this screenshot. I message the bot, which replies to me by a thread. So I can use the thread to start different conversations with ChatGPT at the same time.
<img width="1144" alt="2f0db10e886b7d6bcabe83fd2bf206150df396067a809d9ce53bad7b78d6a89f" src="https://github.com/satorijs/satori/assets/828837/d16259a1-68d6-4c36-a299-e6d17fb43c76">


I find the document about this. [The Reply API](https://open.larksuite.com/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/reply) can do it. I don't know how to integrate this useful function into the Koishi elegantly.

I also [wrote a bot](https://github.com/tzwm/botbotbotbot) before, which is very similar to the Koishi. I moved to the Koishi until I found it and liked it. The only one I missed is this thread function.

**Comment by tzwm** [comment]
I first used `thread` through the new function of Slack at that time. 
You can find more descriptions about `thread` in [the Slack document](https://slack.com/help/articles/115000769927-Use-threads-to-organize-discussions-).

**Comment by MaikoTan** [comment]
So you're talking about the **reply** feature. I thought this feature have been implemented before as long as there is a `quote` element with a valid message id.

Here's the reference code, is there something I missed out?
https://github.com/satorijs/satori/blob/6060d00c563d4c523b733098029840421d97c4eb/adapters/lark/src/message.ts#L25-L31

**Comment by tzwm** [comment]
Thanks! This may be what I need. I will try it……
