### ISSUE TITLE
QQ频道无法回复图片类消息，文字可正常发送

### ISSUE THREAD

**Issue by Atest-1** [satorijs/satori#113]
![image](https://github.com/satorijs/satori/assets/126960324/7c8329e5-0cae-4691-ac13-80b3798a013e)
![9F21247903A7CA9A2F80D9EE02DB55F9](https://github.com/satorijs/satori/assets/126960324/0b6c2d30-1710-4c51-8c53-8ad7dbbf21fc)
![image](https://github.com/satorijs/satori/assets/126960324/22b84f96-f785-4291-86c2-91b5b272e664)
提示url不支持，但并没有挂代理等

**Comment by NWYLZW** [comment]
你需要申请官方的 image url domain 通过才可（但是很明显，pixiv 是不会让你通过的

**Comment by shigma** [comment]
> 你需要申请官方的 image url domain 通过才可（但是很明显，pixiv 是不会让你通过的

是说 QQ 频道不能发任意链接的图片吗？（只能发白名单内的）

**Comment by NWYLZW** [comment]
> > 你需要申请官方的 image url domain 通过才可（但是很明显，pixiv 是不会让你通过的
> 
> 是说 QQ 频道不能发任意链接的图片吗？（只能发白名单内的）

是的，除非自己搓一个 proxy 或者暂存于本地发送

**Comment by NWYLZW** [comment]
当时说是加个配置项来着，因为这个行为，如果走默认 url 传递
就不怎么会消耗 bot 的流量，如果下载下来的话就走的都是机器人的流量了

而且相当于改默认行为，不是很好

用户调用的时候自己下载下来然后给我 buffer 怎么样？因为我是能接受 dataurl、Buffer 类型的数据的

**Comment by shigma** [comment]
> 用户调用的时候自己下载下来然后给我 buffer 怎么样？因为我是能接受 dataurl、Buffer 类型的数据的

这更坏啊，因为有的适配器天生能发所有链接，当然应该是不天生能发链接的适配器补全短板。
