### ISSUE TITLE
adapter-mail插件停止后，日志也一直在刷邮箱连接失败 

### ISSUE THREAD

**Issue by imAkisa** [satorijs/satori#115]
启用邮箱适配器后，右下角邮箱登录是灰色的，然后我停止了插件，但日志依然一直在汇报登录邮箱失败，只能重启koishi才能停止登录邮箱
![邮件适配器bug](https://github.com/satorijs/satori/assets/108515435/2bbe5bd7-1d10-4e06-bec3-ee378002e3c5)

**Comment by shigma** [comment]
cc @Anillc 

疑似 onClose 里对 bot.status 状态判断有误，IMAP 反复重连所致。

**Comment by shigma** [comment]
此问题已修复，但需要等待 Koishi 的版本更新。
