### ISSUE TITLE
Feature Request:给adapter-mail一个自定义名称

### ISSUE THREAD

**Issue by imAkisa** [satorijs/satori#116]
可不可以给邮箱一个自定义名称，能让他在右下角绿灯登录状态能显示名称，在Q群的status也能显示名称

现在他是这样的
![邮箱名字](https://github.com/satorijs/satori/assets/108515435/ccd26f98-fc18-4994-82c4-30bede26bb9b)
![邮箱名字2](https://github.com/satorijs/satori/assets/108515435/34c626d9-b321-41aa-81a1-8e855390ad86)

**Comment by shigma** [comment]
请尝试最新版本。

PS #115 不是连接失败了吗，是怎么解决的？

**Comment by imAkisa** [comment]
连接失败是outlook那边需要手动同意服务器的ip登录邮箱，没同意的话就会登录失败，#115 是想说没同意登录的情况下，邮箱适配器停不下来了
