### ISSUE TITLE
Kook types 问题

### ISSUE THREAD

**Issue by Kabuda-czh** [satorijs/satori#121]
![image](https://github.com/satorijs/satori/assets/62021214/1d058f78-129f-448a-a59d-c3efd0a66c02)

与代码中描述不一致
[core](https://github.com/satorijs/satori/blob/master/adapters/kook/src/types.ts#L432)
```ts
export declare enum Permissions {
    GUILD_ADMIN = 0,
    GUILD_MANAGE = 1,
    GUILD_LOG = 2,
    GUILD_INVITE_CREATE = 3,
    GUILD_INVITE_MANAGE = 4,
    CHANNEL_MANAGE = 5,
    GUILD_USER_KICK = 6,
    GUILD_USER_BAN = 7,
    GUILD_EMOJI_MANAGE = 8,
    GUILD_USER_NAME_CHANGE = 9,
    GUILD_ROLE_MANAGE = 10,
    CHANNEL_VIEW = 11,
    CHANNEL_MESSAGE = 12,
    CHANNEL_MANAGE_MESSAGE = 13,
    CHANNEL_UPLOAD = 14,
    CHANNEL_VOICE_CONNECT = 15,
    CHANNEL_VOICE_MANAGE = 16,
    CHANNEL_MESSAGE_AT_ALL = 17,
    CHANNEL_MESSAGE_REACTION_CREATE = 18,
    CHANNEL_MESSAGE_REACTION_FOLLOW = 19,
    CHANNEL_VOICE_CONNECT_PASSIVE = 20,
    CHANNEL_VOICE_SPEAK_KEY_ONLY = 21,
    CHANNEL_VOICR_SPEAK_FREE = 22,
    CHANNEL_VOICE_SPEAK = 23,
    GUILD_USER_DEAFEN = 24,
    GUILD_USER_NAME_CHANGE_OTHER = 25,
    GUILD_USER_MUTE = 26,
    CHANNEL_VOICE_BGM = 27
}
```

**Comment by Kabuda-czh** [comment]
在 [获取频道详情](https://developer.kookapp.cn/doc/http/channel#%E8%8E%B7%E5%8F%96%E9%A2%91%E9%81%93%E8%AF%A6%E6%83%85) 中
![image](https://github.com/satorijs/satori/assets/62021214/be039cdb-c56f-4c8c-ae44-92a89f063310)
`permission_overwrites` 应该是数组
与代码不一致
[core](https://github.com/satorijs/satori/blob/master/adapters/kook/src/types.ts#L280)

在 [获取用户详情](https://developer.kookapp.cn/doc/http/user#%E8%8E%B7%E5%8F%96%E7%9B%AE%E6%A0%87%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF) 中
![image](https://github.com/satorijs/satori/assets/62021214/1e22bf4c-eadc-4e62-9892-5afaedda3f73)
`Kook.User` 结构缺失
[core](https://github.com/satorijs/satori/blob/master/adapters/kook/src/types.ts#L225)

**Comment by shigma** [comment]
他们老改 API 💢
