### ISSUE TITLE
Bug(discord, kook): url 为 127.0.0.1 的图片发不出去

### ISSUE THREAD

**Issue by idanran** [satorijs/satori#139]
例子：
```
[ Element { type: 'image', attrs: { url: 'http://127.0.0.1:5140/chrono/7262237915369254695', chronoUnsafeIsemoji: true, chronoUnsafeFilepath: 'C:\\Users\\28648\\Documents\\Tencent Files\\507053289\\nt_qq\\nt_data\\Emoji\\emoji-recv\\2023-08\\Ori\\a756a4032261ad2ea846b707865cdbfc.jpg', chronoUnsafeFiletype: '1000' }, children: [] } ]
```

**Comment by shigma** [comment]
目前 @chronocat/koishi-plugin-adapter 无法支持图片转发。你可以选择：

- 部署到公网，这样 chronocat 的图片就具有访问性了
- 等待 chronocat 和 discord 和 kook 插件同时支持 internal URL

**Comment by idanran** [comment]
> 目前 @chronocat/koishi-plugin-adapter 无法支持图片转发。你可以选择：
> 
> * 部署到公网，这样 chronocat 的图片就具有访问性了
> * 等待 chronocat 和 discord 和 kook 插件同时支持 internal URL

可是 telegram 没有这个问题

**Comment by shigma** [comment]
Satori 不应该下载所有要发送图片，因为这会大幅降低性能。绝大多数图片是不需要下载的。

然而，如果不下载就无法知道此图片是否具备可访问性。因此我们需要引入黑/白名单或者 Internal URL，以准确判断 URL 的类型。

Telegram 不是另外做了处理，是不得不下载所有图片，所以不会遇到问题。

**Comment by idanran** [comment]
> Satori 不应该下载所有要发送图片，因为这会大幅降低性能。绝大多数图片是不需要下载的。
> 
> 然而，如果不下载就无法知道此图片是否具备可访问性。因此我们需要引入黑/白名单或者 Internal URL，以准确判断 URL 的类型。
> 
> Telegram 不是另外做了处理，是不得不下载所有图片，所以不会遇到问题。

当然可以不用下载所有的图片，只下载 127.0.0.1 的就行了。

**Comment by shigma** [comment]
dc 我已经修了，kook 需要你帮忙抓个包，随便发一张图片然后拿到 url。可以吗？

**Comment by idanran** [comment]
> dc 我已经修了，kook 需要你帮忙抓个包，随便发一张图片然后拿到 url。可以吗？

我现在身边没有电脑，暂时帮不了。

**Comment by shigma** [comment]
你什么时候能发的时候发一下即可。

**Comment by idanran** [comment]
> 你什么时候能发的时候发一下即可。

嗯呐
