### ISSUE TITLE
Bug(core): WsClient 无法正常 stop

### ISSUE THREAD

**Issue by Hieuzest** [satorijs/satori#153]
由于最新的改动

https://github.com/satorijs/satori/blob/8f06f3bfeb076056666ca77e5a55d4760a017d2d/packages/core/src/bot.ts#L97-L99

导致调用bot.stop()后WsClient中socket onclose时status已经为offline，从而没有退出而是进入了reconnect
https://github.com/satorijs/satori/blob/798ea7bb72dc36c0fa48dffbfcfbab4d0e4b4dcf/packages/core/src/adapter.ts#L73-L78

**Comment by shigma** [comment]
感觉应该把条件改成是 disconnect 或者是 offline。

**Comment by Hieuzest** [comment]
那就得看会不会有adapter手动offline了 比如我看dc里似乎就有

https://github.com/satorijs/satori/blob/798ea7bb72dc36c0fa48dffbfcfbab4d0e4b4dcf/adapters/discord/src/ws.ts#L94-L98

**Comment by shigma** [comment]
手动 offline 不影响这里判断吧
