### ISSUE TITLE
Bug(discord?): `Universal.GuildMember` from `getGuildMemberIter` has invaild avatar URL

### ISSUE THREAD

**Issue by Seidko** [satorijs/satori#155]
### desciption
`Universal.GuildMember` from `getGuildMemberIter` has invaild avatar URL
### screenshot
![image](https://github.com/satorijs/satori/assets/64234553/d9c3102f-4e90-4dc9-9f32-acc0037bbcf0)
---
![image](https://github.com/satorijs/satori/assets/64234553/c37908e7-8dcd-4ad9-b96d-1382f6ef33db)

**Comment by shigma** [comment]
已修复，不过需要等到下一个版本实装。
