### ISSUE TITLE
Feature: 可以给qq频道适配器加一个'slash:是否启用斜线指令。'吗

### ISSUE THREAD

**Issue by imAkisa** [satorijs/satori#157]
![image](https://github.com/satorijs/satori/assets/108515435/609f81e8-92b0-42a5-8870-da442504bd0d)
我看tg的适配器有这个，qq频道也同样是需要斜线唤醒指令

**Comment by shigma** [comment]
qq 频道的斜线指令需要用户自己设置，tg 是有 API 的。

**Comment by imAkisa** [comment]
![image](https://github.com/satorijs/satori/assets/108515435/8f5acfe3-be4d-47ba-be6c-f9dff9b34fe0)
好吧那就只能这样了
