### ISSUE TITLE
QQ 适配器中多余的 escape

### ISSUE THREAD

**Issue by GEEKiDoS** [satorijs/satori#182]
remark 防止有人忘了(

小剧场:
![image](https://github.com/satorijs/satori/assets/14933408/ef92ca2a-96b7-43cc-b2a3-67b7baff962b)

**Comment by MaikoTan** [comment]
> LTC: 册那，吾戆特了一刚.jpg

**Comment by shigma** [comment]
Fixed by https://github.com/satorijs/satori/commit/45b1ffa180d25abb6bd04937c90b0666d3d02d25
