### ISSUE TITLE
无法发送群消息

### ISSUE THREAD

**Issue by super1207** [satorijs/satori#184]
我对接gocq，向QQ群里发送消息，但是提示500 Internal Server Error，其它接口正常。koishi的log没有异常反应。
有这个群，并且能获取群资料：
![image](https://github.com/satorijs/satori/assets/30586004/d5028fa3-4a83-480d-a149-93ae2b8486ee)
发消息提示：
![image](https://github.com/satorijs/satori/assets/30586004/e02046f2-923a-4fa9-b8c8-1a0bb2a1e1fb)
gocq那边显示（账号并没有被风控，其它插件，包括koishi的echo插件都能正常使用）：
![image](https://github.com/satorijs/satori/assets/30586004/4670e06f-8eda-4b8c-9b29-895d712f995a)

版本：
koishi：4.15.6
server-satiri：2.3.1
adapter-onebot：6.1.4

**Comment by MaikoTan** [comment]
Did you having problems with any other adapters? If not, it might be the issue of the `adapter-onebot` itself, since `adapter-onebot` was in a [separated repository](https://github.com/koishijs/koishi-plugin-adapter-onebot), you might need to open an issue there.

**Comment by super1207** [comment]
试了下kook adapter，能正常发送消息，看起来问题没在satori，我先关掉这个issue。
