### ISSUE TITLE
Bug: server-satori 没有将接收到的 satori 资源元素转换为 koishi 资源元素

### ISSUE THREAD

**Issue by idanran** [satorijs/satori#198]
https://satori.js.org/zh-CN/protocol/elements.html#%E8%B5%84%E6%BA%90%E5%85%83%E7%B4%A0

**Comment by idanran** [comment]
> 后续应该使用协议规定的元素实现适配器，旧适配器将进行迁移。

大概是什么时候呢

**Comment by shigma** [comment]
近期。
