### ISSUE TITLE
Feature: koishi 图片元素增加 satori 图片元素的 `width` 和 `height` 属性

### ISSUE THREAD

**Issue by idanran** [satorijs/satori#200]
https://satori.js.org/zh-CN/protocol/elements.html#%E5%9B%BE%E7%89%87

**Comment by shigma** [comment]
我没有看出来需要改动任何地方。这两个属性是可选的，意味着任何适配器都不应该实现，除非平台主动提供了这两个字段。

**Comment by idanran** [comment]
https://koishi.chat/zh-CN/api/message/elements.html#%E5%9B%BE%E7%89%87
我的意思是，在这里加上那两个可选的属性。

**Comment by shigma** [comment]
那你应该往文档提 issue 才对哦（

行我知道了。
