### ISSUE TITLE
Bug: adapter-kook 发送消息后的返回信息无content字段

### ISSUE THREAD

**Issue by Nyayurn** [satorijs/satori#202]
![image](https://github.com/satorijs/satori/assets/132195516/125b0a8d-b53f-4e32-a29c-a289ca8b6ed4)
![image](https://github.com/satorijs/satori/assets/132195516/535c2d47-18fa-42d0-ad61-c430960c5d99)

**Comment by shigma** [comment]
嗯，好像挺多适配器都缺这个。我会尽快修复。
