### ISSUE TITLE
Bug: adapter-mail 发送消息报错 500

### ISSUE THREAD

**Issue by Nyayurn** [satorijs/satori#206]
![image](https://github.com/satorijs/satori/assets/132195516/7c5ef18e-423c-4d7a-b2af-50e284443a3f)
图中为 Nyayurn@outlook.com 向 a15274550902@163.com 发送消息

**Comment by Anillc** [comment]
#206 修复了发送消息的问题，但是你遇到的是另一个问题。

outlook 使用了 starttls, 你需要设置 outlook 的端口为 `587` 并关闭 `tls` 选项。starttls 会在握手时自动启用加密。
