### ISSUE TITLE
Bug：_.session.kook.author_id 不写.d可取，但代码检查要求_.session.kook.d.author_id

### ISSUE THREAD

**Issue by teatube** [satorijs/satori#212]
![image](https://github.com/satorijs/satori/assets/20319737/6e5b1d6a-2fc0-4298-a2a9-245ab6fd3a43)

``` typescript
  ctx.command('p','平台内函数测试')
  .action(async(_)=>{
    if (_.session.kook) {
      _.session.kook.createMessage({
        content: '测试内容',
        target_id: _.session.kook.author_id
     })
    }
  })
```

![image](https://github.com/satorijs/satori/assets/20319737/34787eef-a0c2-4b1a-9aa3-effc345ebebd)
![image](https://github.com/satorijs/satori/assets/20319737/ca7bc39e-110c-4a55-a88b-56c32caf05d1)

System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.10.0
    npm: 9.2.0

Koishi:
    Core: 4.16.2
    Console: 5.22.6
    
    
![image](https://github.com/satorijs/satori/assets/20319737/8856f9fa-521a-4991-9eab-6126f7b90a45)

**Comment by shigma** [comment]
已修复此问题。

你不需要改代码，我把类型改对了。
