### ISSUE TITLE
kook私聊频道类型被认为是语音频道

### ISSUE THREAD

**Issue by super1207** [satorijs/satori#218]
![image](https://github.com/satorijs/satori/assets/30586004/c1d1e0b6-e410-4f8b-8527-850dea056d86)

![image](https://github.com/satorijs/satori/assets/30586004/790ec75b-fab5-444a-a72c-b25ec588a845)

测试方法，kook上给bot私发一条消息。

版本（截止今天，所有依赖都是最新的）：
adapter-kook 4.3.4
server-satori 2.4.0

除此之外，还有一个相关的疑惑：如果既是文本频道又是私聊频道，那么频道类型应该是什么呢？

**Comment by shigma** [comment]
文本频道特指非私聊的文本频道，私聊频道就是私聊频道。之后可以优化一下文档。

**Comment by shigma** [comment]
更正：文档有误，1 是私聊 3 是语音

**Comment by ilharp** [comment]
改文档，并且尽快改
