### ISSUE TITLE
Cordis 类型 Breaking Changes 导致继承  Service 的派生框架 config 类型错误

### ISSUE THREAD

**Issue by CyanChanges** [satorijs/satori#239]
在三天前的一次 commit 中, cordis 修改了 Service 的类型参数(这应该是 Breaking Changes), 
从原来的 `<C extends Context = Context>` 变成了 `<T = unknown, C extends Context = Context>` (`T` 为 config 参数的类型, C 为上下文的类型)
https://github.com/cordiverse/cordis/commit/7e9e3786df8e2780618368e9ef6301a48cbb9f8f#diff-1c6afc22918abe7f393db70d13a55eeebaaac02aa76c8d90133562bffcd9312bR34

这将导致原本 Satori 继承的 `cordis.Service` 传入的 `C`( = Context) 将对于 cordis 中的 `T` (config 类型)
![image](https://github.com/satorijs/satori/assets/68551684/e7c4f6f5-ca52-4986-9fec-1ef6a888ae19)

导致原本的 config 参数类型必须 extends Context, 导致插件继承服务的时候类型出错

**Comment by shigma** [comment]
只会影响 Satori 和 Koishi。我下个版本会修。

**Comment by CyanChanges** [comment]
应该修好了
