### ISSUE TITLE
(Bug?): adapter-satori 连接成功后不显示机器人昵称

### ISSUE THREAD

**Issue by wyapx** [satorijs/satori#257]
如题，连接成功后没有显示机器人昵称（已经按Satori协议标准提供Nickname和Avatar，头像正常显示）

![图片](https://github.com/satorijs/satori/assets/26220729/9f6060dd-c805-4de7-abab-df86626289a0)

login.get返回的数据(数据做脱敏处理)：
```
{
  'status': 1, 
  'user': {
    'id': '{uin}', 
    'nick': '是名字!', 
    'avatar': 'https://q1.qlogo.cn/g?b=qq&nk={uin}&s=640'
  }, 
  'self_id': '{uin}', 
  'platform': 'nekobox'
}
```

**Comment by shigma** [comment]
就用 name 即可，不用 nick。

![Uploading image.png…]()

**Comment by wyapx** [comment]
问题已修复，感谢
