### ISSUE TITLE
Bug: network error while adapter connecting cause process exit

### ISSUE THREAD

**Issue by Seidko** [satorijs/satori#265]
![Image_1713461841153](https://github.com/satorijs/satori/assets/64234553/0ba925a5-d0ce-4fb5-8ba8-f3bc3709ce03)

[reproduce code](https://github.com/kaenbyoujs/kaenbyou/tree/66a644fad703c54820eaf84c21fdad585a16d2e8)

**Comment by shigma** [comment]
Fixed by https://github.com/satorijs/satori/commit/8737af957481b585feb211fea8ec13fd80503c2e
