### ISSUE TITLE
adapter-qq 无法发送链接形式的silk语音文件

### ISSUE THREAD

**Issue by jackz0722** [satorijs/satori#274]
4.5.0以后的版本增加了本地发送base64后的silk语音文件 但是链接类型的silk语音文件无法发送
![image](https://github.com/satorijs/satori/assets/84524966/88ada4fa-d2f5-4b6a-b9b8-2d0732f04777)

**Comment by shigma** [comment]
根据提示，你需要自行安装 silk 服务。

**Comment by jackz0722** [comment]
发送的已经是silk格式的文件还需要再次转码嘛？

**Comment by shigma** [comment]
adapter-qq 会下载并检测文件格式，报这个错说明检测出并非合法的 SILK 文件。

**Comment by jinghuashang** [comment]
> 根据提示，你需要自行安装 silk 服务。

请问有silk的安装教程吗，ubuntu貌似没有这个包
