### ISSUE TITLE
bug: discord创建子区和删除子区后会adapter-discord会报错

### ISSUE THREAD

**Issue by Cola-Ace** [satorijs/satori#306]
discord创建子区和删除子区后会报图片中的错误，adapter-discord的版本为4.5.7
![PixPin_2024-08-09_22-23-55](https://github.com/user-attachments/assets/3e7d11fc-a66f-4aee-b93d-fae7a68ba363)

![PixPin_2024-08-09_22-23-48](https://github.com/user-attachments/assets/3d847334-0444-4cbe-a448-c87aba8e624b)

**Comment by shigma** [comment]
4.5.8
