### ISSUE TITLE
[BUG] wecom无法正常使用

### ISSUE THREAD

**Issue by Ewall555** [satorijs/satori#313]
#292 
相同问题，适配器异常，能接受消息，不返回消息，输入help不返回，沙盒模式正常，debug日志如下
![微信图片_20240828094106](https://github.com/user-attachments/assets/efd27fc8-abab-4220-a1ea-9011c82eb725)

**Comment by DoiiarX** [comment]
我回调API确认都不成功。兄弟有遇到吗？
