### ISSUE TITLE
adapter-qq 更新至 4.19.0 ，websocket 连接方式 报错 【当前配置项不满足约束，请检查配置！】

### ISSUE THREAD

**Issue by shangxueink** [satorijs/satori#330]
在 更新 adapter-qq 至 4.19.0 之后，

使用 webhook 的 连接方式，可以正常开启插件

![image](https://github.com/user-attachments/assets/2a81a679-a372-46f4-bfae-e91588c069f4)

---

但是如果此时 关闭插件，切换到【websocket】连接方式

除此以外一模一样的配置，却不能开启插件了，会提示

```
当前配置项不满足约束，请检查配置！
```

![image](https://github.com/user-attachments/assets/1202af5e-7af9-4591-a1c9-95fcb3a1b561)

---

似乎仅在 4.19.0 版本的 adapter-qq 才出现

---

期望

可以支持【websocket】连接方式下 开启插件

**Comment by idranme** [comment]
https://github.com/satorijs/satori/commit/2c9aa14af6687b1dc9b3cadc5b3fbfc9401cdb8a#diff-4500da00047f8a24a3864b03a2a82ecf4138488f6acdd6bc007eb450b9a17323L104

可能跟这里有关

**Comment by shigma** [comment]
@idranme union 的情况下，如果有默认值，默认值一侧不能设置为 required

**Comment by shangxueink** [comment]
啊？？？？


修好了吗？

可是我一个小火箭 更新到 4.19.1 问题依然存在


![image](https://github.com/user-attachments/assets/7dec4465-2866-4a9f-8f0d-fce859b87a97)



![image](https://github.com/user-attachments/assets/3f347bd4-9768-4bc9-be88-37c266ae82c5)

**Comment by shangxueink** [comment]
> 可是我一个小火箭 更新到 4.19.1 问题依然存在

呜呜呜，好像还是没修好唔

**Comment by shangxueink** [comment]
看到了 adapter-qq 的 4.19.1 的更新

但是我翻阅了 ->  https://www.npmjs.com/package/@satorijs/adapter-qq?activeTab=code


但是似乎在 @satorijs/adapter-qq 的 index.cjs 里面，`websocket` 配置项还是 `.required()`

其中 第 549 行 左右

```
((WsClient2) => {
  WsClient2.Options = import_core2.Schema.intersect([
    import_core2.Schema.object({
      protocol: import_core2.Schema.const("websocket").required()
    }),
    import_core2.Adapter.WsClientConfig
  ]);
})(WsClient || (WsClient = {}));
```
发现其中还是
```
protocol: import_core2.Schema.const("websocket").required()
```


---


实测也是 不可开启 websocket 的状态

> 可是我一个小火箭 更新到 4.19.1 问题依然存在

---
