### ISSUE TITLE
RFC: Telegram file proxy server

### ISSUE THREAD

**Issue by shigma** [satorijs/satori#41]
### Basic design

```ts
interface FilesConfig {
  endpoint?: string
  local?: string
  // added
  server?: string
}
```

新增配置项 `config.files.server`，表示是否启用文件代理服务。默认值为 `/telegram/file`。

- 如果路径为空或未配置 `selfUrl`，则不会启用文件代理服务；所有文件在发送前将先进行下载
- 启用文件代理服务后，将在 `/telegram/file/${file_id}` 代理相应的文件；所有文件会在发送前替换 url 为上述地址

### To be discussed

- 存在多个 bot 时是否需要区分？还是默认使用其中的一个？
- 没有在线 bot 时此服务的返回值是什么？

**Comment by Anillc** [comment]
#46 中实现的会注册 `/telegram/selfId` 的路由，每个 bot 都有自己的路由（telegram 的 token 分两部分，selfId 是前部分，同时也是 bot 的 id）

没有在线的 bot 的时候就没有路由，请求这个 api 会 404
