### ISSUE TITLE
Bug: empty content

### ISSUE THREAD

**Issue by XxLittleCxX** [satorijs/satori#47]
https://github.com/satorijs/satori/blob/cfb492680a360a48d2c4e88b5d14f762a9477477/packages/core/src/session.ts#L70-L72

Specific events, e.g. `message-deleted`

### Steps to reproduce

```
ctx.exclude(session => session.content?.startsWith("//"))
```

**Comment by shigma** [comment]
已修复，新版本将于一周内发布。
