### ISSUE TITLE
Feature: 增加 KOOK 适配器更多事件支持

### ISSUE THREAD

**Issue by modcrafts** [satorijs/satori#49]
https://github.com/satorijs/satori/blob/cca82a172aca34917cf8126a6b9f0d070ad05e35/adapters/kook/src/types.ts#L58
增加对列表中 `NoticeType` 的 `Event` 支持
此处的一些事件并无法在 `ctx.on()` 中使用，例如 `added_channel`

**Comment by shigma** [comment]
已加入 [Koishi 4.12 Iteration Plan](https://github.com/koishijs/koishi/issues/1000)。
