### ISSUE TITLE
Distinguish between `voice` and `sound`.

### ISSUE THREAD

**Issue by lychees** [satorijs/satori#54]
In some IM, the context distinguishes `voice` and `sound`.

![image](https://user-images.githubusercontent.com/2507027/206868556-325e32dd-0213-495f-b3fb-b550fd0f661d.png)

![T )H $A_FWYR@I%_U M%_$W](https://user-images.githubusercontent.com/2507027/206868538-27972105-26b2-4c5e-a0c2-3d214eecc563.png)

Take `telegram` as an example, the `voice` has more UI/UX support, while `sound` is just send a file.
But it's a matter related to platform, e.g. the supported file types might be different.

**Comment by undefined-moe** [comment]
Commonly, the first one is called voice(or sound), and the second one is simply sending a mp3 file (or called attachment).

**Comment by ilharp** [comment]
支持 `<audio>` 和 `<file>`

不过群里好像有人反馈 OneBot 平台收到的语音类型是 `record`？OneBot 后续会不会有 `record` 收到自动转 `audio` 的功能

**Comment by shigma** [comment]
> 不过群里好像有人反馈 OneBot 平台收到的语音类型是 record？OneBot 后续会不会有 record 收到自动转 audio 的功能

onebot 的 `record` 相当于 satori 的 `audio`，发送的时候会自动转。

**Comment by ilharp** [comment]
> > 不过群里好像有人反馈 OneBot 平台收到的语音类型是 record？OneBot 后续会不会有 record 收到自动转 audio 的功能
> 
> onebot 的 `record` 相当于 satori 的 `audio`，发送的时候会自动转。

是的  所以收到的时候是不是也应该自动转一下  有群友反馈收到是 `record`

![5G`P97EAYQD M{I}RH9$_86](https://user-images.githubusercontent.com/20179549/211140813-a8ef3073-fe63-4e1f-90f5-6b628833b610.jpg)
