### ISSUE TITLE
Bug: Adapter-kaiheila 显示已连接,Bot已上线,接受不到信息（Chat也无）

### ISSUE THREAD

**Issue by takaqiao** [satorijs/satori#6]
### Describe the bug

RT
WS协议
![image](https://user-images.githubusercontent.com/13859193/173732328-464eb46a-38b5-46af-a7ec-cd43e640b82b.png)
开黑啦客户端显示已上线
![image](https://user-images.githubusercontent.com/13859193/173732369-0563d320-e4cf-4799-a12e-8cf8da94f1e1.png)
后台显示无错误
![image](https://user-images.githubusercontent.com/13859193/173732415-bd55bb9c-100d-463e-a13f-1e7eed851432.png)
Chat也接受不到信息
Chat中不显示相关频道
数据库里也没有相关channel
机器人显示的是绿灯运行中
服务器权限已全给
![image](https://user-images.githubusercontent.com/13859193/173734242-868e5875-8088-47db-8269-4bf561bddbd1.png)

### Steps to reproduce

1.创建一个机器人
2.填Token选WS
3.邀请到服务器
4.随便打字
5.啥也没有

### Expected behavior

我希望他能接收到信息:?

### Screenshots

![image](https://user-images.githubusercontent.com/13859193/173732328-464eb46a-38b5-46af-a7ec-cd43e640b82b.png)
![image](https://user-images.githubusercontent.com/13859193/173732369-0563d320-e4cf-4799-a12e-8cf8da94f1e1.png)
![image](https://user-images.githubusercontent.com/13859193/173732415-bd55bb9c-100d-463e-a13f-1e7eed851432.png)
![image](https://user-images.githubusercontent.com/13859193/173734230-acb76c78-17d4-41e8-97aa-8dd93f4b74a9.png)

### Versions

- OS: Windows 10
- Platform: Kaiheila
- Node version: 16.15.1
- Koishi version: 4.7.4

**Comment by memset0** [comment]
感觉 [这段](https://github.com/satorijs/satori/blob/4215191d364b865440059d3b131651e4bfd15100/adapters/kook/src/bot.ts#L18-L33) 有点锅锅。

临时解决方法可在配置文件里手动写 headers，格式参照 [Kook 的官方文档](https://developer.kookapp.cn/doc/reference)。

**Comment by memset0** [comment]
Should be fixed in the newest version, closed.
