### ISSUE TITLE
Feature: 企业微信支持

### ISSUE THREAD

**Issue by NWYLZW** [satorijs/satori#8]
如题

**Comment by purerosefallen** [comment]
https://code.mycard.moe/3rdeye/koishi-plugin-adapter-wecom

There was one, but still on 4.7.6.

You migrate it to Satori by youself.

**Comment by beetcb** [comment]
any updates on this thread? @NWYLZW 
saw self-assigned, is there an ongoing pr WIP?

**Comment by beetcb** [comment]
> Maybe I'll work on it in the future. 

If WeCom bots can be used in WeChat, the robot restrictions of WeChat account might be elegantly solved.
In this case, spending time on development seems more attractive, even though there may not be many WeCom users, there are many WeChat users.


@shigma

**Comment by MaikoTan** [comment]
> If WeCom bots can be used in WeChat

Seems not possible currently.

The `WeCom` adapter is using the `Bot` interface to contact with people, but only a valid `WeCom` account (using by a real personne) could contact with users from WeChat.

**Comment by shigma** [comment]
以实现。
