### ISSUE TITLE
WARNING]: 登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 Code: 237

### ISSUE THREAD

**Issue by themis0009** [satorijs/satori#98]
-_-

或者是45版本过低错误
求大佬技术支持@_@

**Comment by themis0009** [comment]
WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45

**Comment by shigma** [comment]
这是 gocq 相关问题，请前往 go-cqhttp 仓库提交 issue。

PS 如果你在使用 koishi-plugin-gocqhttp，可以参考 <https://k.ilharp.cc/810>
